{:stir_kx=>
  {:should_include=>"true",
   :description=>"Wavenumber of antennae",
   :help=>"Wavenumber of antennae.",
   :code_name=>:kx,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :stir_ky=>
  {:should_include=>"true",
   :description=>"Wavenumber of antennae",
   :help=>"Wavenumber of antennae",
   :code_name=>:ky,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer},
 :stir_kz=>
  {:should_include=>"true",
   :description=>"Wavenumber of antennae",
   :help=>"Wavenumber of antennae",
   :code_name=>:kz,
   :must_pass=>
    [{:test=>"kind_of? Integer",
      :explanation=>"This variable must be an integer."}],
   :type=>:Integer}}
